name: Beta

on:
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          url: ${{ secrets.REGISTRY_URL }}
          image: ysbakker/discord-github-preview
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.url }}/${{ env.image }}:experimental
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
